org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

org.gradle.configuration-cache=false

minecraft_version=1.21.11
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_kotlin_version=1.13.13+kotlin.2.4.10

version=1.0.0
group=studio.sniffa

fabric_api_version=0.141.6+1.21.11

owo_version=0.13.0+1.21.11

geckolib_version=5.4.2
